on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

name: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          cargo build --release --locked
          cp target/release/kermars kermars-$TARGET
          tar -cvzf kermars-$TARGET.tgz kermars-$TARGET LICENSE
        env:
          TARGET: x86_64-unknown-linux-gnu
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kermars-x86_64-unknown-linux-gnu.tgz
